/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.SocketClient.View;

import com.mvc.view.AbstractViewPanel;
import java.awt.Color;
import java.awt.Graphics;
import java.beans.PropertyChangeEvent;

/**
 *
 * @author MonkeyBreath
 */
public class MarkerView extends AbstractViewPanel {

    private int x=0;
    private int y=0;
    private int radius = 5;
    
    private Color color;
    
    /**
     * Creates new form MarkerView
     */
    public MarkerView() {
        initComponents();
    }
    
    public MarkerView(Color color) {
        this();
        
        this.color = color;
    }

    // TODO: Move into model and react to model changes
    public void setRadius(int radius) {
        this.radius = radius;
        repaint();
    }
    
    // TODO: Move into model and react to model changes
    public void setColor(Color c) {
    	this.color = c;
    	repaint();
    }
    
    // TODO: Move into model and react to model changes
    public void setPosition(int x, int y) {
    	this.x = x;
    	this.y = y;
    	repaint();
    }    
    
    public void paintComponent(Graphics g) {
    	g.setColor(color);
    	g.fillOval(x, y, (radius*2), (radius*2));
    	g.setColor(Color.BLACK);
    	g.drawOval(x, y, radius*2, radius*2);
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void modelPropertyChange(PropertyChangeEvent pce) {
    }
}
